"""add user_id column

Revision ID: c03c6c188a4b
Revises: 3f8a9291c338
Create Date: 2025-12-14 21:02:23.343853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03c6c188a4b'
down_revision: Union[str, Sequence[str], None] = '3f8a9291c338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
