"""create ctegories table, add foreign_key

Revision ID: ae449fa6e92e
Revises: 043e29d8ceb9
Create Date: 2025-12-10 14:11:32.027428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae449fa6e92e'
down_revision: Union[str, Sequence[str], None] = '043e29d8ceb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ctegory_id', 'categories', ['Category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ctegory_id', type_='foreignkey')

    # ### end Alembic commands ###
